### ISSUE TITLE
Request for the R Script Article

### ISSUE THREAD

**Issue by 1667857557** [opain/eQTL_to_TWAS#8]
Dear Mr. Henry,

I want to express my gratitude for your excellent work. By the way, would it be possible for you to share the article regarding this R script with us? We are eager to gain more insights into this project. Unfortunately, the GitHub link did not lead us to the correct website.

Thank you for your time and consideration.

Huang
Email: [huangyufeng@sxmu.edu.cn]

**Comment by 1667857557** [comment]
we found it! https://www.biorxiv.org/content/10.1101/2022.11.23.517213v1.full

**Comment by opain** [comment]
Thank you for reaching out. I have now updated the link on the README.
